name: Build RISC-V
on:
  push:
    branches:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt install gcc-riscv64-linux-gnu && sudo apt install make

      - name: Build
        run: make riscv
